image: conanio/gcc8:latest

before_script:
  - pip install conan
  - sudo apt-get -qq update && sudo apt-get install unzip -y --no-install-recommends

run:
  script:
    - conan remote add upload_repo ${CONAN_REMOTE}
    - conan user -r upload_repo ${CONAN_USERNAME}
    - conan create . demo/stable
    - conan upload foo/0.1.0@demo/stable --all --force -r upload_repo
