image: conanio/gcc8:latest

before_script:
  - pip install git+https://github.com/czoido/conan.git@feature/tqdm_output
  - sudo apt-get -qq update && sudo apt-get install unzip -y --no-install-recommends

run:
  script:
    - conan_server &
    - wget https://github.com/pocoproject/conan-poco/archive/master.zip
    - unzip master.zip
    - cd conan-poco-master/
    - conan create . demo/stable
    - conan remote add conan-local http://0.0.0.0:9300
    - conan user -r conan-local -p demo demo
    - conan upload Poco/1.9.0@demo/stable --all -r conan-local
