build: false

environment:
    PYTHON: "C:\\Python37"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install git+https://github.com/czoido/conan.git@feature/tqdm_output
  - conan user

test_script:
  - ps: Start-Process conan_server -PassThru
  - conan create . demo/stable
  - conan remote add conan-local http://0.0.0.0:9300
  - conan user -r conan-local -p demo demo
  - conan upload foo/0.1.0@demo/stable --all -r conan-local
