build: false

environment:
    PYTHON: "C:\\Python37"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install git+https://github.com/czoido/conan.git@feature/tqdm_output
  - conan user

test_script:
  - ps: Start-Process conan_server -PassThru
  - curl -fsS -o 1.70.0.zip https://github.com/conan-community/conan-boost/archive/release/1.70.0.zip
  - 7z x 1.70.0.zip
  - cd conan-boost-release-1.70.0/
  - conan create . demo/stable
  - conan remote add conan-local http://0.0.0.0:9300
  - conan user -r conan-local -p demo demo
  - conan upload boost/1.70.0@demo/stable --all -r conan-local
