build: false

environment:
    PYTHON: "C:\\Python37"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user

test_script:
  - conan remote add upload_repo %CONAN_REMOTE%
  - conan user -r upload_repo %CONAN_USERNAME%
  - conan create . demo/stable
  - conan upload foo/0.1.0@demo/stable --all --force -r upload_repo